/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  overviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
  ],

  hardwareSidebar: [
    {
      type: 'autogenerated',
      dirName: 'hardware',
    },
  ],

  softwareSidebar: [
    {
      type: 'autogenerated',
      dirName: 'software',
    },
  ],

  designSidebar: [
    {
      type: 'autogenerated',
      dirName: 'design',
    },
  ],
};

module.exports = sidebars;
