/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  overviewSidebar: [
    {
      type: 'autogenerated',
      dirName: 'overview',
    },
  ],

  hardwareSidebar: [
    {
      type: 'autogenerated',
      dirName: 'hardware',
    },
  ],

  pinmappingSidebar: [
    {
      type: 'autogenerated',
      dirName: 'pin-mapping',
    },
  ],

  componentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'components',
    },
  ],

  requirementsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'requirements',
    },
  ],
};

module.exports = sidebars;
